# Generated by Django 2.2 on 2020-09-25 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catatan',
            name='upload_img',
        ),
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_img', models.ImageField(blank=True, default='', upload_to='images/')),
                ('catatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='catatan.Catatan')),
            ],
        ),
    ]
