# Generated by Django 2.2 on 2020-09-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0002_auto_20200925_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catatan',
            name='ket',
            field=models.TextField(help_text='maksimal 500 kata', max_length=500),
        ),
    ]
