# Generated by Django 2.2 on 2020-10-01 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkl',
            name='nama_dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membimbing', to=settings.AUTH_USER_MODEL),
        ),
    ]
